spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8082
          predicates:
            - Path= /users/**
        - id: r2
          uri: http://localhost:8081
          predicates:
            - Path= /organizations/**
        - id: r3
          uri: http://localhost:8083
          predicates:
            - Path= /donations/**


#
#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
